# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kraliken-nextjs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Debug - Check build output
        run: |
          ls -la
          ls -la .next || echo ".next directory not found"


      - name: Zip artifact for deployment
        run: |
          mkdir deploy
          [ -d .next ] && cp -R .next deploy/ || echo "Warning: .next directory not found"
          [ -d public ] && cp -R public deploy/ || echo "Warning: public directory not found"
          cp package.json package-lock.json deploy/
          [ -f server.js ] && cp server.js deploy/ || echo "No server.js found"
          [ -d node_modules ] && cp -R node_modules deploy/ || echo "No node_modules found"
          cd deploy
          ls -la  # Debug: mit másoltunk át
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7B4D4AFC53124993AB52EE3243FB0C38 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_61877B06B7AB4FDC92D3C0CB9284F906 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3701B2FF594F460C839467E86E6979AD }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kraliken-nextjs'
          slot-name: 'Production'
          package: .
          